"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision = '1841c7498153'
down_revision = 'h9i0j1k2l3m4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：此迁移主要是同步注释和索引，核心表结构已在之前迁移中创建
    
    # 1. 更新 ai_detection_logs 字段注释
    try:
        op.alter_column('ai_detection_logs', 'algorithm_details',
                   existing_type=mysql.TEXT(),
                   comment='技术细节JSON，如: {face_swap: 0.9}',
                   existing_nullable=True)
    except Exception as e:
        print(f"跳过 ai_detection_logs.algorithm_details 注释更新: {e}")
    
    # 2. 删除旧索引（如果存在）
    try:
        op.drop_index('idx_detection_logs_call_type', table_name='ai_detection_logs')
    except:
        pass
    try:
        op.drop_index('idx_detection_logs_hash', table_name='ai_detection_logs')
    except:
        pass
    try:
        op.drop_index('idx_detection_logs_type', table_name='ai_detection_logs')
    except:
        pass
    
    # 3. 更新 chat_messages 字段注释
    try:
        op.alter_column('chat_messages', 'speaker',
                   existing_type=mysql.VARCHAR(length=20),
                   comment='说话人: user/other/system',
                   existing_nullable=False)
    except:
        pass
    try:
        op.alter_column('chat_messages', 'timestamp',
                   existing_type=mysql.DATETIME(),
                   comment='消息实际发送/发生时间（由客户端或任务系统提供）',
                   existing_nullable=True,
                   existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    except:
        pass
    try:
        op.alter_column('chat_messages', 'created_at',
                   existing_type=mysql.DATETIME(),
                   comment='数据库入库时间（系统自动生成）',
                   existing_nullable=True,
                   existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    except:
        pass
    
    # 4. chat_messages 索引调整
    try:
        op.drop_index('ix_chat_messages_sequence', table_name='chat_messages')
    except:
        pass
    try:
        op.create_index(op.f('ix_chat_messages_message_id'), 'chat_messages', ['message_id'], unique=False)
    except:
        pass
    
    # 5. 更新 family_groups 字段注释
    try:
        op.alter_column('family_groups', 'admin_id',
                   existing_type=mysql.INTEGER(),
                   comment='主管理员ID',
                   existing_nullable=False)
    except:
        pass
    
    # 6. 删除 owner_id 索引（需要先处理外键依赖）
    # 注意：owner_id 索引可能被外键约束依赖，跳过删除
    # try:
    #     op.drop_index('owner_id', table_name='family_groups')
    # except:
    #     pass
    
    # 7. 更新 message_logs 外键约束
    try:
        op.drop_constraint('message_logs_ibfk_1', 'message_logs', type_='foreignkey')
        op.create_foreign_key(None, 'message_logs', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    except:
        pass
    
    # 8. 更新 user_memories 字段注释和索引
    try:
        op.alter_column('user_memories', 'memory_type',
                   existing_type=mysql.VARCHAR(length=30),
                   comment='记忆类型',
                   existing_nullable=False)
    except:
        pass
    try:
        op.drop_index('ix_user_memories_importance', table_name='user_memories')
    except:
        pass
    try:
        op.drop_index('ix_user_memories_user_type', table_name='user_memories')
    except:
        pass
    try:
        op.create_index(op.f('ix_user_memories_memory_id'), 'user_memories', ['memory_id'], unique=False)
    except:
        pass
    
    # 9. 更新 users 表字段注释
    try:
        op.alter_column('users', 'family_id',
                   existing_type=mysql.INTEGER(),
                   comment='所属家庭组ID（普通成员只能有一个）',
                   existing_nullable=True)
    except:
        pass
    try:
        op.alter_column('users', 'is_admin',
                   existing_type=mysql.TINYINT(display_width=1),
                   comment='是否为某家庭组的管理员',
                   existing_nullable=True,
                   existing_server_default=sa.text("'0'"))
    except:
        pass
    
    # 10. 更新 users 外键约束
    try:
        op.drop_constraint('fk_user_family', 'users', type_='foreignkey')
        op.create_foreign_key(None, 'users', 'family_groups', ['family_id'], ['id'], ondelete='SET NULL')
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_user_family', 'users', 'family_groups', ['family_id'], ['id'])
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否为家庭管理员(监护人)',
               existing_comment='是否为某家庭组的管理员',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'family_id',
               existing_type=mysql.INTEGER(),
               comment='所属家庭组ID',
               existing_comment='所属家庭组ID（普通成员只能有一个）',
               existing_nullable=True)
    op.drop_index(op.f('ix_user_memories_memory_id'), table_name='user_memories')
    op.create_index('ix_user_memories_user_type', 'user_memories', ['user_id', 'memory_type'], unique=False)
    op.create_index('ix_user_memories_importance', 'user_memories', ['importance'], unique=False)
    op.alter_column('user_memories', 'memory_type',
               existing_type=mysql.VARCHAR(length=30),
               comment='记忆类型: fraud_experience/alert_response/preference/risk_pattern',
               existing_comment='记忆类型',
               existing_nullable=False)
    op.drop_constraint(None, 'message_logs', type_='foreignkey')
    op.create_foreign_key('message_logs_ibfk_1', 'message_logs', 'users', ['user_id'], ['user_id'])
    op.create_index('owner_id', 'family_groups', ['admin_id'], unique=False)
    op.alter_column('family_groups', 'admin_id',
               existing_type=mysql.INTEGER(),
               comment='组长/创建者ID',
               existing_comment='主管理员ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.create_index('ix_chat_messages_sequence', 'chat_messages', ['call_id', 'sequence'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='数据库入库时间（系统自动生成）',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_messages', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment='消息时间',
               existing_comment='消息实际发送/发生时间（由客户端或任务系统提供）',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_messages', 'speaker',
               existing_type=mysql.VARCHAR(length=20),
               comment='说话人: user/other',
               existing_comment='说话人: user/other/system',
               existing_nullable=False)
    op.create_index('idx_detection_logs_type', 'ai_detection_logs', ['detection_type'], unique=False)
    op.create_index('idx_detection_logs_hash', 'ai_detection_logs', ['ocr_dialogue_hash'], unique=False)
    op.create_index('idx_detection_logs_call_type', 'ai_detection_logs', ['call_id', 'detection_type', 'created_at'], unique=False)
    op.alter_column('ai_detection_logs', 'algorithm_details',
               existing_type=mysql.TEXT(),
               comment='技术细节JSON，如: {"face_swap": 0.9, "lip_sync": 0.8}',
               existing_comment='技术细节JSON，如: {face_swap: 0.9}',
               existing_nullable=True)
    # ### end Alembic commands ###
