"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '2e76a6d68123'
down_revision = '6ae724be076f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_url', sa.String(length=500), nullable=True),
    sa.Column('fraud_type', sa.String(length=100), nullable=True),
    sa.Column('target_group', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_id'), 'knowledge_items', ['id'], unique=False)
    op.create_table('user_learning_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('learned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_learning_records_id'), 'user_learning_records', ['id'], unique=False)
    op.create_index(op.f('ix_user_learning_records_item_id'), 'user_learning_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_learning_records_user_id'), 'user_learning_records', ['user_id'], unique=False)
    #op.drop_index('owner_id', table_name='family_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('owner_id', 'family_groups', ['admin_id'], unique=False)
    op.drop_index(op.f('ix_user_learning_records_user_id'), table_name='user_learning_records')
    op.drop_index(op.f('ix_user_learning_records_item_id'), table_name='user_learning_records')
    op.drop_index(op.f('ix_user_learning_records_id'), table_name='user_learning_records')
    op.drop_table('user_learning_records')
    op.drop_index(op.f('ix_knowledge_items_id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    # ### end Alembic commands ###
