"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '5f0f690bd683'
down_revision = '617a43371be9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_logs_call_id'), 'message_logs', ['call_id'], unique=False)
    op.create_index(op.f('ix_message_logs_id'), 'message_logs', ['id'], unique=False)
    op.add_column('users', sa.Column('role_type', sa.String(length=20), nullable=True, comment='角色类型(如老人、儿童、学生、青壮年)'))
    op.create_index(op.f('ix_users_role_type'), 'users', ['role_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_type'), table_name='users')
    op.drop_column('users', 'role_type')
    op.drop_index(op.f('ix_message_logs_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_call_id'), table_name='message_logs')
    # ### end Alembic commands ###
