"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision = '617a43371be9'
down_revision = '49d04f5bfe7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_records',
    sa.Column('call_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('caller_number', sa.String(length=20), nullable=True, comment='来电号码'),
    sa.Column('platform', sa.Enum('PHONE', 'WECHAT', 'VIDEO_CALL', 'QQ', 'OTHER', name='callplatform'), nullable=True, comment='通话平台'),
    sa.Column('target_name', sa.String(length=100), nullable=True, comment='对方昵称/备注'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='通话开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='通话结束时间'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='通话时长(秒)'),
    sa.Column('detected_result', sa.Enum('SAFE', 'SUSPICIOUS', 'FAKE', name='detectionresult'), nullable=True, comment='检测结果(safe/suspicious/fake)'),
    sa.Column('audio_url', sa.String(length=500), nullable=True, comment='录音文件URL'),
    sa.Column('video_url', sa.String(length=500), nullable=True, comment='视频文件URL(如果是视频通话)'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='视频封面/关键帧截图'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_call_records_call_id'), 'call_records', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_records_user_id'), 'call_records', ['user_id'], unique=False)
    op.create_table('ai_detection_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False, comment='对应通话ID'),
    sa.Column('voice_confidence', sa.Float(), nullable=True, comment='声音伪造置信度(0-1)'),
    sa.Column('video_confidence', sa.Float(), nullable=True, comment='图像伪造置信度(0-1)'),
    sa.Column('text_confidence', sa.Float(), nullable=True, comment='文本诈骗话术置信度(0-1)'),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='综合风险评分(0-100)'),
    sa.Column('detected_keywords', sa.Text(), nullable=True, comment='检测到的敏感词(JSON)'),
    sa.Column('evidence_snapshot', sa.String(length=500), nullable=True, comment='违规画面截图URL'),
    sa.Column('time_offset', sa.Integer(), nullable=True, comment='异常发生的通话秒数'),
    sa.Column('algorithm_details', sa.Text(), nullable=True, comment='技术细节(JSON,如FaceSwap/LipSync)'),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='使用的模型版本'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='检测时间'),
    sa.ForeignKeyConstraint(['call_id'], ['call_records.call_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_ai_detection_logs_call_id'), 'ai_detection_logs', ['call_id'], unique=False)
    op.create_index(op.f('ix_ai_detection_logs_log_id'), 'ai_detection_logs', ['log_id'], unique=False)
    op.drop_index('ix_message_logs_call_id', table_name='message_logs')
    op.drop_index('ix_message_logs_id', table_name='message_logs')
    op.drop_index('ix_message_logs_user_id', table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='接收用户'),
    sa.Column('call_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='关联通话ID'),
    sa.Column('msg_type', mysql.VARCHAR(length=20), nullable=False, comment='消息类型'),
    sa.Column('risk_level', mysql.VARCHAR(length=20), nullable=True, comment='风险等级'),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False, comment='消息标题'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='消息内容'),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否已读'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='message_logs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_message_logs_user_id', 'message_logs', ['user_id'], unique=False)
    op.create_index('ix_message_logs_id', 'message_logs', ['id'], unique=False)
    op.create_index('ix_message_logs_call_id', 'message_logs', ['call_id'], unique=False)
    op.drop_index(op.f('ix_ai_detection_logs_log_id'), table_name='ai_detection_logs')
    op.drop_index(op.f('ix_ai_detection_logs_call_id'), table_name='ai_detection_logs')
    op.drop_table('ai_detection_logs')
    op.drop_index(op.f('ix_call_records_user_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_call_id'), table_name='call_records')
    op.drop_table('call_records')
    # ### end Alembic commands ###
