"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision = '64ce3837fdec'
down_revision = '6aa208783993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_applications_id'), 'family_applications', ['id'], unique=False)
    op.alter_column('family_groups', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='组长/创建者ID',
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('family_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(None, 'family_groups', 'users', ['owner_id'], ['user_id'])
    op.alter_column('users', 'family_id',
               existing_type=mysql.INTEGER(),
               comment='所属家庭组ID',
               existing_comment='家庭组ID',
               existing_nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否为家庭管理员(监护人)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否为家庭管理员(监护人)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'family_id',
               existing_type=mysql.INTEGER(),
               comment='家庭组ID',
               existing_comment='所属家庭组ID',
               existing_nullable=True)
    op.drop_constraint(None, 'family_groups', type_='foreignkey')
    op.alter_column('family_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('family_groups', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_comment='组长/创建者ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_family_applications_id'), table_name='family_applications')
    op.drop_table('family_applications')
    # ### end Alembic commands ###
