"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '6ae724be076f'
down_revision = 'db6210aa7cd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('analysis', sa.Text(), nullable=True, comment='大模型对通话内容的完整分析'))
    op.add_column('call_records', sa.Column('advice', sa.Text(), nullable=True, comment='大模型针对用户画像给出的专属防骗建议'))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('owner_id', 'family_groups', ['admin_id'], unique=False)
    op.drop_column('call_records', 'advice')
    op.drop_column('call_records', 'analysis')
    # ### end Alembic commands ###
