"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision = '9099b41fead6'
down_revision = '69383949bed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('family_groups', 'admin_id',
               existing_type=mysql.INTEGER(),
               comment='组长/创建者ID',
               existing_comment='创建者ID',
               existing_nullable=False)
    #op.drop_index('owner_id', table_name='family_groups')
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True, comment='性别(男/女/未知)'))
    op.add_column('users', sa.Column('profession', sa.String(length=50), nullable=True, comment='职业'))
    op.add_column('users', sa.Column('marital_status', sa.String(length=20), nullable=True, comment='婚姻状况(单身/已婚/离异)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'profession')
    op.drop_column('users', 'gender')
    #op.create_index('owner_id', 'family_groups', ['admin_id'], unique=False)
    op.alter_column('family_groups', 'admin_id',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_comment='组长/创建者ID',
               existing_nullable=False)
    # ### end Alembic commands ###
