"""add admin tables

Revision ID: c3d4e5f6g7h8
Revises: 6aa208783993
Create Date: 2026-03-18 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6g7h8'
down_revision: Union[str, None] = '6aa208783993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='管理员用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='角色: admin/super_admin/operator'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='账号是否激活'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    
    op.create_table('admin_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True, comment='管理员ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('resource', sa.String(length=50), nullable=True, comment='操作对象'),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='对象ID'),
    sa.Column('details', sa.Text(), nullable=True, comment='操作详情'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='操作时间'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_admin_logs_log_id'), 'admin_logs', ['log_id'], unique=False)
    
    op.create_table('system_monitor',
    sa.Column('monitor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False, comment='指标名称'),
    sa.Column('metric_value', sa.String(length=100), nullable=False, comment='指标值'),
    sa.Column('metric_type', sa.String(length=20), nullable=True, comment='指标类型: count/percentage/duration'),
    sa.Column('category', sa.String(length=30), nullable=True, comment='分类: general/detection/user/performance'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='记录时间'),
    sa.PrimaryKeyConstraint('monitor_id')
    )
    op.create_index(op.f('ix_system_monitor_monitor_id'), 'system_monitor', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_monitor_monitor_id'), table_name='system_monitor')
    op.drop_table('system_monitor')
    op.drop_index(op.f('ix_admin_logs_log_id'), table_name='admin_logs')
    op.drop_table('admin_logs')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
