"""add fraud_type to call_records

Revision ID: d4e5f6g7h8i9
Revises: 5b146b306f80
Create Date: 2026-03-18 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e5f6g7h8i9'
down_revision: Union[str, None] = '5b146b306f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('fraud_type', sa.String(length=50), nullable=True, comment='诈骗类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_records', 'fraud_type')
    # ### end Alembic commands ###
