"""
Alembic迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'db6210aa7cd2'
down_revision = '9099b41fead6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_detection_logs_ibfk_1', 'ai_detection_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_detection_logs', 'call_records', ['call_id'], ['call_id'], ondelete='CASCADE')
    #op.drop_index('owner_id', table_name='family_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('owner_id', 'family_groups', ['admin_id'], unique=False)
    op.drop_constraint(None, 'ai_detection_logs', type_='foreignkey')
    op.create_foreign_key('ai_detection_logs_ibfk_1', 'ai_detection_logs', 'call_records', ['call_id'], ['call_id'])
    # ### end Alembic commands ###
